// Custom service worker for push notifications
// This extends the workbox service worker generated by vite-plugin-pwa

self.__WB_DISABLE_DEV_LOGS = true;

import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets
precacheAndRoute(self.__WB_MANIFEST || []);

self.addEventListener('push', (event) => {
  console.log('[Service Worker] Push Received.');

  let data = { title: 'Fanfare Notification', body: 'You have a new notification' };

  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data.body = event.data.text();
    }
  }

  const options = {
    body: data.body,
    icon: '/icon-192.png',
    badge: '/badge.png',
    vibrate: [100, 50, 100],
    data: {
      dateOfArrival: Date.now(),
      primaryKey: data.primaryKey || 1,
      url: data.url || '/'
    }
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

self.addEventListener('notificationclick', (event) => {
  console.log('[Service Worker] Notification click received.');

  event.notification.close();

  event.waitUntil(
    clients.openWindow(event.notification.data.url || '/')
  );
});
